### PR TITLE
Make the goal pose tool magenta

### PR DESCRIPTION
**Pull request by iwanders**
This makes it easier to distinguish from the set pose tool.

magenta_goal

For some reason I didn't have the power to push a new branch into clearpathrobotics/rviz, so had to make a PR to merge it into the branch we use.

@mikepurvis, You touched this branch last :)
@jasonimercer, @efernandez , @p6chen, @servos for some autonomy eyes to decide whether we like this.

### CODE REVIEW

**Comment by jasonimercer** [comment]
Looks good to me.

:+1:

**Comment by iwanders** [comment]
Upstream PR is [filed](https://github.com/ros-visualization/rviz/pull/1520).

**Review by efernandez — APPROVED** [review]

**Comment by efernandez** [comment]
@iwanders Works for me. I'm not going to discuss whether magenta is a good choice or not. :smile: 

I can merge it, should I? Or should I wait for another :+1: ?

**Comment by iwanders** [comment]
I think it's good to merge. I'll do it and tag it. Thanks for giving this :+1: all.

**Pull request merged**
